services:
  db:
    image: postgres:16-alpine
    container_name: doculens-db
    environment:
      POSTGRES_DB: doculensdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - doculens-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d doculensdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: no

  api:
    build: .
    container_name: doculens-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/doculensdb
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - doculens-net
    restart: no

volumes:
  db-data:
    name: doculens-pg-data

networks:
  doculens-net:
    name: doculens-net
    driver: bridge
